---
title: Etiquette
---

## Use of Content Warnings

Content Warnings (CW) hide parts of toots, 
can be opened with the click of a button, 
and individual users can set CWs to open by default. 
CW are useful to:

1) Empower readers who are sensitive to particular subjects to actively decide when to engage with those subjects,
2) keep subjects that may not interest everyone as an opt-in option, and/or
3) keep timelines easier to read.

Content Warnings should be used for topics including, but not limited to:

* Triggering content
	* reports or news about sexual assault, harassment, violence, racism, antisemitism, LGBTQIA+-phobia, burnout, etc.
* Glorification of over-working
* Common phobia-triggering animal media (e.g. spiders, snakes, sharks). 

CWs are a useful tool for managing your content.
You can use CWs when posting about material you think might not
be of broad interest or might take too much visual space.
For example, job postings will primarily be of interest
to folks looking for that particular job,
so you could use a CW to give the general job type/title and let
interested readers expand the post to see more details (see also [use of hashtags](#use-of-hashtags)). 

In this context it can be helpful to think of CW as
representing "Content Wrap" rather than Content Warning. 

**Please also read [Regarding attempts to abuse these anti-abuse tools and policies](./rules.html#rules-abuse-callout).**


## Describe the media you post

Written descriptions of photos and videos you post are a really important way to increase
the accessibility of Mastodon for visually impaired people.

When posting media (pictures or videos), click the edit button and a window will
allow you to enter a short written description.
This is sometimes also referred to as "alt text" or "alternative text".

A nice way to ensure this is to subscribe to a bot that will remind you when you forget alt-text,
such as [PleaseCaption@botsin.space](https://botsin.space/@PleaseCaption).

Here is a good guide on
[how to write an image description](https://uxdesign.cc/how-to-write-an-image-description-2f30d3bf5546)
by [Alex Chen](https://www.alexyingchen.com/).

## Use of hashtags

Hashtags are how content from users you do not follow can be discovered on Mastodon, since the text content of toots
is generally not searchable (in most cases anyway; in all cases it requires additional algorithms/software/infrastructure to do so).

Given that consideration, we encourage the use of hashtags to classify and broaden the potential reach of the content you share.

Hashtags should use the CamelCase format, where words are separated by upper cases, like so: `#ThisNewHashtagIsGreat`.
This can aid in their readability both by people and by screen readers.

A list of hashtags that could be used on [ecoevo.social](https://ecoevo.social/about):

* `#JobOffer` when posting a job offer of any kind, add more hashtags to precise level
	`#Faculty`, `#Postdoc`, `#PhdPosition`, `#Technician`, etc.; and 
	subjects such as `#Ecology`, `#Labwork`, or `#Modeling`. See [Job postings section](#job-postings).
* `#Internship` to advertise an internship, precise subjects similar to job offers
* `#Conference` to advertise a conference
* `NewPaper` or `#Preprint` for new research results
* `#rstats` or `#python` or other languages for coding questions or resources

## Job postings

When posting job ads keep in mind that the search tool is only using hashtags,
it is therefore the most important part of your posting.

Try to follow these guidelines:

1) Use [hashtags](#use-of-hashtags), always use `#Job` and a set of [standardized hashtags](#job-standardized-hashtags) (don't forget to use CamelCase);
1) use `CW` on your post with a summary subject line, such as "Job ad: PhD marine ecology – Berlin Germany" (don't use hashtags in CW as they are not searchable there);
1) optionally, finish by tagging any relevant group(s) such as `@jobsecoevo@a.gup.pe` if your offer is in `#EcoEvo`.


#### Example of job standardized hashtags: {#job-standardized-hashtags}

* Always use: `#Job`
* Level/Type: `#phd`, `#postdoc`, `#TenureTrack`, `#lectureship`, `#fellowship`, `#master`, ...
* Main field: `#ecology`, `#evolution`, `#genomics`, ... 
* Subject-related keywords, for example: `#birds`, `#disease`, `#biodiversity`, ...
* Country: `#France`, `#USA`, `#Germany`, ...


## Threads

When posting a thread:

1. Set your first post to be **Public** (visible for all)
2. Then, reply to your first post and set the visibility to **Unlisted** (visible for all, but opted-out of discovery features)
3. Continue your thread by replying to the last post and the visibility will automatically be set as **Unlisted** unless you change it

It is considerate to use the `i/n` indication at the end or beginning of your posts to better indicate this is a thread,
where `i` is the number of the current toot in the thread and `n` is the total number of toots. You can keep it as a
literal `n` if you don't know the total number of toots. This approach is similar to the convention people use at the bird site.
