---
title: Introduction
---

:::{.callout-note}
This guide is under active development and things will definitely change over time.

This is also designed to be a community-built resource.
Please check out the [Contributing](./how-to-contribute.html) page for more information.
:::

# Introduction

**Rules to respect, etiquette, and general things to know about the 
[ecoevo.social](https://ecoevo.social/about) server and [Mastodon](#what-is-mastodon) in general.**

[ecoevo.social](https://ecoevo.social/about) is a Mastodon server dedicated to the biological Ecology and Evolution community.
This is broadly defined; everyone who is connected to those topics is welcome.

[ecoevo.social](https://ecoevo.social/about) is administered by [Alexis Simon](https://ecoevo.social/@alxsim).
This is volunteer work, and as such there may occasionally be some issues along the road that are not resolved immediately.
Please be patient if issues arise, as we are all learning together how to best develop this community and space.

If you are in a position to do so, you can contribute financially for the maintenance of the server
through [Open Collective](https://opencollective.com/ecoevosocial).

The infrastucture of [ecoevo.social](https://ecoevo.social/about) 
is maintained by [masto.host](https://masto.host) and physically hosted by OVH in France.
Their terms of service can be found [here](https://masto.host/tos).
Status of the server can be seen [here](https://status.masto.host/),
[ecoevo.social](https://ecoevo.social/about) is hosted on App Server 9 and Database 8.

Enjoy connecting!

## What is Mastodon?

[Mastodon](https://joinmastodon.org/) is a federated microblogging platform. You can read more about it in its [documentation](https://docs.joinmastodon.org/).

## About privacy

A safe internet user is an informed internet user.

The [privacy policy](https://ecoevo.social/terms) indicates what will be enforced regarding privacy.

:::{.callout-warning}
## Important considerations about privacy

Posts on Mastodon are not end-to-end encrypted. Do not share any sensitive information over Mastodon.
For more details, see the [privacy policy](https://ecoevo.social/terms).

You must be aware that Mastodon data, both public and direct messages,
are accessible by server operators and receiving servers 
(for example if you send a direct message to someone on another server).

Quoted from the [privacy policy](https://ecoevo.social/terms):

> We may also release your information when we believe release is appropriate to comply
> with the law, enforce our site policies, or protect our or others' rights, property, or safety.

If you need to have truly private conversations with someone else that contain sensitive information,
we suggest you use another application offering end-to-end encryption and privacy. One good option is [Signal](https://signal.org).
:::

## Data backup policy

As per our host [masto.host ToS](https://masto.host/tos/):

> Data backups are daily, but media backups do not include remote cache. If a disaster restore is needed, over 24 hours of data could be missing, and it could take several days to bring the service back online.

> As mentioned on the my.masto.host backup page, you should regularly download the backup of your server as backups are not stored offline, and in the event of a catastrophic failure, your copy of the backups may be the only way to restore the server. Masto.host is in open beta and offered with no warranty.

As masto.host does not offer a third off-site backup at this time,
the admin will manually download the database backup as regurlarly as possible.
This backup is stored privately and encrypted on a remote AWS S3 server.
Manual backups will not include media posted on the instance.

Please be aware that in case of catastrophic server failure,
more than 24h of data and all media could be lost.


## Resources for Getting Started with Mastodon and the Fediverse

* [Everything I know about Mastodon, by Danielle Navarro](https://blog.djnavarro.net/posts/2022-11-03_what-i-know-about-mastodon)
* [Mastodon documentation](https://docs.joinmastodon.org/)
* [Mastodon quick start guide](https://blog.joinmastodon.org/2018/08/mastodon-quick-start-guide/)
* [A Brief Mastodon Guide for Social Media Worriers, by Per Axbom](https://axbom.com/mastodon-guide/)
* [Fedi Tips - An Unofficial Guide to Mastodon and the Fediverse](https://fedi.tips)
