---
title: Rules
---

By using ecoevo.social, you agree to abide by the following rules:

1. No racism, sexism, homophobia, transphobia, xenophobia, or casteism
2. No incitement of violence or promotion of violent ideologies
3. No harassment, dogpiling, or doxxing of other users
4. No intentional sharing of false or misleading information
5. No posting of sexually explicit or violent media
6. No content that is considered illegal in France and/or Germany

::: {.callout-warning}
## Regarding attempts to abuse these anti-abuse tools and policies {#rules-abuse-callout}

Following the [Scholar Social community’s guidlines](https://scholar.social/about/more#regarding-attempts-to-abuse-these-anti-abuse-tools-and-policies):

> “Do not attempt to weaponize our Community Standards or anti-abuse tools/policies against marginalized groups
> such as people of colour, women or queer people. Users of [ecoevo.social] are expected to have the literacy to
> understand that "reverse discrimination" is not real, and so attempts to re-centre discussions of marginalized
> people around the feelings of the privileged will be taken as manipulative behaviour undertaken deliberately in bad-faith.
> (E.g. white people should not demand that people of colour put CW's on every discussion of race;
> a straight person who reports a queer person for writing "I hate straight people"
> may find their own account suspended.)”
:::


They are not set in stone and community-suggested changes in wording or the addition of rules is welcomed.
See the section [How to contribute](./how-to-contribute.html).

In addition to the community guidelines we put in place, the hosting service we are using, [masto.host](https://masto.host/), has its own terms of service as well. They can be found [here](https://masto.host/tos/).